---
title: "HW 1 - Codes"
output: html_notebook
---
```{r}
#Libraries
library(tidyverse)
library(naniar)
library(ggcorrplot)
library(caret) 

#Data Sets Upload
setwd("/Users/eylulruyagullu/Desktop/BOUN'4/IE582/hw1_files")
input_data <- read.csv("hw1_input.csv", header = TRUE)
real_data <- read.csv("hw1_real.csv", header = TRUE)
img_data <- read.csv("hw1_img.csv", header = TRUE)

#Missing Data Control
cat("Input Data Missing Values:", sum(is.na(input_data)), "\n")
cat("Real Part Data Missing Values:", sum(is.na(real_data)), "\n")
cat("Imaginary Part Data Missing Values:", sum(is.na(img_data)), "\n")

#Number of Rows Control
cat("Input Data Row Count:", nrow(input_data), "\n")
cat("Real Part Data Row Count:", nrow(real_data), "\n")
cat("Imaginary Part Data Row Count:", nrow(img_data), "\n")

```

```{r}
frequencies <- seq(23, 33, length.out = ncol(real_data))

s11_magnitude <- sqrt(real_data^2 + img_data^2)
column_variances <- apply(s11_magnitude, 2, var)
selected_indices <- order(column_variances, decreasing = TRUE)[1:4]  
selected_frequencies <- frequencies[selected_indices]

real_selected <- real_data[, selected_indices]
img_selected <- img_data[, selected_indices]

selected_frequencies

plot(frequencies, column_variances, type = "l", col = "blue", 
     xlab = "Frequency (GHz)", ylab = "Variance |S11|", main = "Variance S11 Magnitude")
points(selected_frequencies, column_variances[selected_indices], col = "red", pch = 19)

```

```{r}
correlation_matrix <- cor(input_data)  
print(correlation_matrix)


ggcorrplot(correlation_matrix, 
           method = "circle", 
           type = "lower", 
           lab = TRUE, 
           lab_size = 3, 
           colors = c("blue", "white", "red"),
           title = "Correlation Matrix of Decision Variables")

```

```{r}
real_model_26_7 <- lm(real_selected[,1] ~ ., data = input_data)
summary(real_model_26_7)

img_model_26_7 <- lm(img_selected[,1] ~ ., data = input_data)
summary(img_model_26_7)
```

```{r}
real_model_26_7 <- lm(real_selected[,1] ~ ., data = input_data)
summary(real_model_26_7)

real_model_26_75 <- lm(real_selected[,2] ~ ., data = input_data)
summary(real_model_26_75)

real_model_26_8 <- lm(real_selected[,3] ~ ., data = input_data)
summary(real_model_26_8)

real_model_26_85 <- lm(real_selected[,4] ~ ., data = input_data)
summary(real_model_26_8)
```

```{r}
summary_statistics <- function(actual_values, predicted_values) {
  mse <- mean((predicted_values - actual_values)^2)
  rmse <- sqrt(mse)
  mae <- mean(abs(predicted_values - actual_values))
  r2 <- 1 - sum((predicted_values - actual_values)^2) / sum((actual_values - mean(actual_values))^2)
  return(c(MSE = mse, RMSE = rmse, MAE = mae, R2 = r2))
}
```

```{r}

set.seed(123)  
n <- nrow(input_data)
train_index <- sample(1:n, size = 0.7 * n)
train_data <- input_data[train_index, ]
test_data <- input_data[-train_index, ]

cat("Size of Training Set: ", nrow(train_data), "\n")
cat("Size of Test Set: ", nrow(test_data), "\n")

real_model <- lm(real_selected[train_index, 1] ~ ., data = train_data)  
predictions <- predict(real_model, newdata = test_data)
actual_values <- real_selected[-train_index, 1]

plot(actual_values, predictions, main = "Actual vs Predicted", xlab = "Actual Values", ylab = "Predicted Values", col = "blue")
abline(0, 1, col = "red")  # Y=x line (ideal scenario)

summary_statistics(actual_values, predictions)
summary(real_model)

```

```{r}
calculate_mse <- function(actual, predicted) {
  mean((actual - predicted)^2)}
mse_values <- numeric(4)

real_model_1_v2 <- lm(real_selected[train_index, 1] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(real_model_1_v2, newdata = test_data)

actual_values <- real_selected[-train_index, 1]

plot(actual_values, predictions, main = "Actual vs Predicted", xlab = "Actual Values", ylab = "Predicted Values", col = "blue")
abline(0, 1, col = "red") 

summary_statistics(actual_values, predictions)
summary(real_model_1_v2)
mse_values[1] <- calculate_mse(actual_values, predictions)
```

```{r}
#Frequency 2:
real_model_1_v2 <- lm(real_selected[train_index, 2] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(real_model_1_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 2]

summary_statistics(actual_values, predictions)
summary(real_model_1_v2)
mse_values[2] <- calculate_mse(actual_values, predictions)


#Frequency 3:
real_model_1_v2 <- lm(real_selected[train_index, 3] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(real_model_1_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 3]

summary_statistics(actual_values, predictions)
summary(real_model_1_v2)
mse_values[3] <- calculate_mse(actual_values, predictions)

#Frequency 4:
real_model_1_v2 <- lm(real_selected[train_index, 4] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(real_model_1_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 4]

summary_statistics(actual_values, predictions)
summary(real_model_1_v2)
mse_values[4] <- calculate_mse(actual_values, predictions)

average_mse <- mean(mse_values)
cat("Average MSE for all models:", average_mse, "\n")
```

```{r}
img_model <- lm(img_selected[train_index, 1] ~ ., data = train_data)  
predictions <- predict(img_model, newdata = test_data)
actual_values <- img_selected[-train_index, 1]

plot(actual_values, predictions, main = "Actual vs Predicted", xlab = "Actual Values", ylab = "Predicted Values", col = "blue")
abline(0, 1, col = "red")  # Y=x line (ideal scenario)

summary_statistics(actual_values, predictions)
summary(img_model)
```

```{r}
mse_values_2 <- numeric(4)
img_model_v2 <- lm(img_selected[train_index, 1] ~ height.of.substrate + width.of.patch +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(img_model_v2, newdata = test_data)
actual_values <- img_selected[-train_index, 1]

plot(actual_values, predictions, main = "Actual vs Predicted", xlab = "Actual Values", ylab = "Predicted Values", col = "blue")
abline(0, 1, col = "red")  # Y=x line (ideal scenario)

summary_statistics(actual_values, predictions)
summary(img_model_v2)
mse_values_2[1] <- calculate_mse(actual_values, predictions)
```

```{r}
#Frequency 2:
img_model_v2 <- lm(real_selected[train_index, 2] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(img_model_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 2]

summary_statistics(actual_values, predictions)
summary(img_model_v2)
mse_values_2[2] <- calculate_mse(actual_values, predictions)


#Frequency 3:
img_model_v2 <- lm(real_selected[train_index, 3] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(img_model_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 3]

summary_statistics(actual_values, predictions)
summary(img_model_v2)
mse_values_2[3] <- calculate_mse(actual_values, predictions)

#Frequency 4:
img_model_v2 <- lm(real_selected[train_index, 4] ~ height.of.substrate * width.of.patch * dielectric.constant.of.substrate +
                                 radius.of.the.probe + c_probe, data = train_data)  
predictions <- predict(img_model_v2, newdata = test_data)
actual_values <- real_selected[-train_index, 4]

summary_statistics(actual_values, predictions)
summary(img_model_v2)
mse_values_2[4] <- calculate_mse(actual_values, predictions)

average_mse <- mean(mse_values)
cat("Average MSE for all models:", average_mse, "\n")
```

```{r}
input_data_scaled <- scale(input_data)
pca_model <- prcomp(input_data_scaled, center = TRUE, scale. = TRUE)
summary(pca_model)

pca_df <- as.data.frame(pca_model$x)
pca_loadings <- pca_model$rotation

top_features <- list()
for (i in 1:4) {
  top_features[[paste0("PC", i)]] <- head(sort(abs(pca_loadings[, i]), decreasing = TRUE), 5)
}

print(top_features)

variances <- pca_model$sdev^2

variances_explained <- variances / sum(variances)

cat("Explained Variance for the First 4 Components:\n")
explained_variance <- data.frame(
  Component = paste0("PC", 1:4),
  Variance_Explained = variances_explained[1:4],
  Cumulative_Variance = cumsum(variances_explained)[1:4]
)
explained_variance

num_components <- which(cumsum_variances_explained >= 0.5)[1]
cat("Number of Selected Components: ", num_components, "\n")

```

